<a href="https://colab.research.google.com/github/DS-Johnny/Python-para-Dados/blob/main/Numpy_aulas_RodrigoSoaresTadewald.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# AULA 1: introdução


Importando numpy

In [ ]:
import numpy as np

In [ ]:
minha_lista = [1,2,3]

In [ ]:
minha_lista

[1, 2, 3]

Converter lista em array numpy

In [ ]:
np.array(minha_lista)

array([1, 2, 3])

In [ ]:
minha_lista

[1, 2, 3]

Para criar uma lista de duas dimensões:

In [ ]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.arrange cria uma sequência de números

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

array de zeros

In [ ]:
np.zeros(3)

array([0., 0., 0.])

Para fazer uma matriz de zeros utilizar tupla:

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Matriz de "Uns":

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Matriz identidade: Contém "Uns" nas diagonais e zeros no restante da matriz

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

argumentos do arange -> (início, fim, passo)


argumentos do linspace -> (início, fim, quantos números igualmente espaçados dentro da série)

In [ ]:
np.linspace(0,10,2)

array([ 0., 10.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

Números aleatórios:

Rand: cria números aleatórios de 0 a 1, seguindo uma distribuição uniforme

In [ ]:
np.random.rand(5)

array([0.73535417, 0.97557847, 0.12267559, 0.36686186, 0.97211534])

matriz com rand:

In [ ]:
np.random.rand(2,5)

array([[0.93458872, 0.43454517, 0.20250789, 0.68571663, 0.82665224],
       [0.81443367, 0.59506257, 0.79452552, 0.78709322, 0.85720468]])

Randn: A diferença é que a distribuição não é uniforme

In [ ]:
np.random.randn(4)

array([ 1.30922632, -0.63565074,  0.4794846 , -0.29288767])

randint: (inicio, fim, quantidade de números)

In [ ]:
np.random.randint(0, 100, 10)

array([21, 15, 55, 92, 26, 15, 14, 96, 68, 90])

A mesma coisa funcionaria se multiplicar o randn:

In [ ]:
np.random.randn(5) *100

array([  50.28728299, -124.90299452,   74.76949218,   67.83789637,
        -96.4746487 ])

In [ ]:
np.round(np.random.randn(5)*100)

array([  -5., -157.,   10.,  -51.,   53.])

Atributos e métodos do numpy

Reshape:

In [ ]:
arr = np.random.rand(25)

In [ ]:
arr

array([0.84297782, 0.20507373, 0.85361423, 0.18444988, 0.92523286,
       0.56507548, 0.74074004, 0.06536292, 0.52737512, 0.26922961,
       0.38119918, 0.82953519, 0.19006214, 0.91495403, 0.74699793,
       0.40118718, 0.11641595, 0.98324001, 0.8304686 , 0.89912352,
       0.01818322, 0.7792791 , 0.1797083 , 0.06846482, 0.62310157])

In [ ]:
arr.reshape((5,5))

array([[0.84297782, 0.20507373, 0.85361423, 0.18444988, 0.92523286],
       [0.56507548, 0.74074004, 0.06536292, 0.52737512, 0.26922961],
       [0.38119918, 0.82953519, 0.19006214, 0.91495403, 0.74699793],
       [0.40118718, 0.11641595, 0.98324001, 0.8304686 , 0.89912352],
       [0.01818322, 0.7792791 , 0.1797083 , 0.06846482, 0.62310157]])

Atributo shape:

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape((5,5))

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.max()

0.983240007107479

In [ ]:
arr.min()

0.018183221115325887

argmax retorna o índice na qual o maior elemento se encontra

In [ ]:
arr.argmax()

17

In [ ]:
arr.argmin()

20

# AULA 2: indexação e fatiamento de arrays

In [ ]:
arr = np.arange(0,30, 3)

In [ ]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[3]

9

In [ ]:
arr[2:5]

array([ 6,  9, 12])

In [ ]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [ ]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

É possível alterar um valor ou valores de determinados indices atribuindo junto com o fatiamento 

In [ ]:
arr[2:] = 100

In [ ]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

Fatiando matrizes

In [ ]:
arr = np.arange(50).reshape((5,10))

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

O primeiro colchete representa linha, o segundo representa coluna

In [ ]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Atribuir um array à um segundo array, cria uma referência e não uma cópia.

Neste caso, se você alterar algum valor, ele será alterado nos dois arrays

In [ ]:
arr2 = arr[:3]

In [ ]:
arr2[:] = 100


In [ ]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Para evitar isso, utilizar o método copy()

In [ ]:
arr = np.arange(50).reshape((5,10))

In [ ]:
arr2 = arr[:].copy()

In [ ]:
arr2[:3] = 100

In [ ]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Podemos fazer a indexação de arrays de duas dimensões com vírgula também:

[linha,coluna]

In [ ]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

Uma outra notação:

In [ ]:
arr > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
bol = arr <30

In [ ]:
arr[bol]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

EXEMPLOS DIFERENTES:

In [ ]:
array = np.linspace(0, 100, 30)

In [ ]:
array.shape

(30,)

In [ ]:
array = array.reshape(3,10)

In [ ]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [ ]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])

#AULA 3: Operações com Numpy Arrays

In [ ]:
arr = np.arange(0,16)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Para somar arrays é importante que eles tenham o mesmo tamanho

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

Divisão por zero:

em um código python comum, uma divisão por zero resultaria em um erro, porém o numpy é capaz de induzir a uma resposta apenas mostrando uma mensagem de aviso

In [ ]:
arr / arr

<ipython-input-85-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [ ]:
# RuntimeWarning

Operações escalares

In [ ]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [ ]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [ ]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [ ]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [ ]:
np.mean(arr)

7.5

In [ ]:
np.std(arr)

4.6097722286464435

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [ ]:
np.max(arr)

15

In [ ]:
np.min(arr)

0